### ISSUE TITLE
I'm not able to download from the store

### ISSUE THREAD

**Issue by vittbol** [tomer8007/whatsapp-web-incognito#2] opened 2018-01-11 20:29 UTC
I'm not able to download from the store.

**Comment by tomer8007** [comment] 2018-01-11 20:32
I know, that's because Google took it down due to trademark infringement (starts with "WhatsApp"). I renamed the extension and re-published it but it was taken down again without explanation.

I have sent an email to the Chrome Web Store Team. hopefully they will respond quickly so I can bring it back. For now you can clone it from GitHub and install manually.

**Comment by vittbol** [comment] 2018-01-11 20:33
Don't you think it's just Whatsapp messing with you?

**Comment by tomer8007** [comment] 2018-01-11 20:35
The Chrome Web Store Takedown Notice went like

"Hi,

Google was notified that some of your materials allegedly infringe upon the trademarks of others, the details of the removed extension may be found at the end of this message.

Please note that repeated violations may result in a suspension of your Chrome Web Store Publisher account. If you have any further concerns about this issue, please address them directly to the complainant in the Trademark Infringement Notice provided.

The affected extension(s) are listed below:
https://chrome.google.com/webstore/detail/whatsapp-web-incognito/dmojkdggbdjlhgmakakajjbbdibkjkgj
Regards,
The Chrome Web Store Team"

And later down in the email:

"trademark_explain: The app uses the trademarks of WhatsApp without 
authorization, including but not limited to use of "WhatsApp" as the first 
word in the app’s title. "

**Comment by vittbol** [comment] 2018-01-11 20:42
It seems that it was all the fault of the trademark then... I hope they solve it soon.

**Comment by vittbol** [comment] 2018-01-13 13:55
Uh, downloaded, installed, but nothing changes.

**Comment by tomer8007** [comment] 2018-01-13 14:06
From GitHub?
Did you install in developer mode and all that?

**Comment by vittbol** [comment] 2018-01-13 14:10
Yes, downloaded from GitHub. I dragged the folder on the extensions tab, installed, clicked the icon, whatsapp web was open but nothing changed.

**Comment by tomer8007** [comment] 2018-01-13 14:13
I just tried the extension and I think WhatsApp has changed some stuff again (that's the 4th time or so). It does block read receipts but UI elements do not always update as expected. I will have to work on it.

I do see the incognito settings, though. Do you see them?

**Comment by vittbol** [comment] 2018-01-13 14:14
No, I don't see them.

**Comment by tomer8007** [comment] 2018-01-13 14:18
Try extracting these files to a folder and load that one.

[WhatsApp Web Incognito.zip](https://github.com/tomer8007/whatsapp-web-invisible/files/1628417/WhatsApp.Web.Incognito.zip)

**Comment by vittbol** [comment] 2018-01-13 14:39
Still nothing. The icon from Whatsapp Web Incognito shows up on the extension bar, but when I click it and loads the Whatsapp Web, there is no incognito settings.

**Comment by tomer8007** [comment] 2018-01-13 14:39
Anthing interesting in Javascript console?

**Comment by vittbol** [comment] 2018-01-13 14:41
http://prntscr.com/hzwiyr

**Comment by tomer8007** [comment] 2018-01-13 14:45
And I suppose you do have a file called `images/incognito_gray.svg` under the extension directory?

This file is the icon that should show up, and the reference to it is under `styles.css`:
`background-image: url(chrome-extension://__MSG_@@extension_id__/images/incognito_gray.svg) !important;`

**Comment by vittbol** [comment] 2018-01-13 14:49
Can't find that path in styles.css. What should I do?

**Comment by tomer8007** [comment] 2018-01-13 14:51
Don't see anything like this?

![image](https://user-images.githubusercontent.com/11458759/34907079-cbaf6d72-f881-11e7-8f40-53853ab788a4.png)

Maybe upload your `styles.css` so I can see what's going on.

**Comment by vittbol** [comment] 2018-01-13 15:10
Oh, I see now. I was looking in the styles from the Whatsapp web page. LOL

So, yeah, there is a `background-image: url(chrome-extension://__MSG_@@extension_id__/images/incognito_gray.svg) !important;` in `styles.css`

**Comment by tomer8007** [comment] 2018-01-13 15:38
OK, then, and you do have an actual `images/incognito_gray.svg` file, right? The `manifest.json` should also have the line
 `"web_accessible_resources": ["lib/drop/drop.js", "lib/sweetalert/sweetalert.min.js", "core/*", "images/*" ]` in the end.

But this all sounds a bit strange. I would try googling around and playing with paths related stuff. I will try to investigate this further after fixing the new bug I found (caused by WhatsApp Web moving to React.js 16.0)

**Comment by tomer8007** [comment] 2018-01-26 11:36
Update:
---
Google told me to contact WhatsApp, and WhatsApp told me that the name shouldn't include the word "WhatsApp". Will be fixed.

**Comment by jakamoo33** [comment] 2018-01-28 20:42
same problem.

**Comment by tomer8007** [comment] 2018-01-28 21:14
The extension with the changed name was rejected again (trademark stuff).
Please use the version from GitHub manually (in developer mode) until WhatsApp will respond.

If this doesn't work, please let me know. I'm doing whatever I can to bring it back.

**Comment by jakamoo33** [comment] 2018-01-28 21:28
github version don't working dear.

How can I get in contact with you for a project?

**Comment by tomer8007** [comment] 2018-01-29 10:49
Can you give more details?
Do you the same problem described above?

**Comment by jakamoo33** [comment] 2018-01-29 11:10
I dragged the folder to the extensions tab, installed, clicked the icon, whatsapp web was opened but nothing has changed.

and send websocket message, image ?

**Comment by tomer8007** [comment] 2018-01-29 21:46
Wait, is the extension working for you?
If it does, What was the problem?

**Comment by tomer8007** [comment] 2018-02-02 11:49
Alright, this start to be frustrating.
WhtsApp is not very clear as to what exactly is the problem with the extension.
I'm not even sure they're the cause for the extension being taken down.
If nothing changes soon, I'm going to consider re-publishing as a new item.

**Comment by vittbol** [comment] 2018-03-16 12:01
It's working ok here. There is any chance that you can remove the notification on phone that "Whatsapp web is currenctly active"?

**Comment by tomer8007** [comment] 2018-03-16 12:45
Good to hear the extension is working for you.
Unfortunately I think the "Whatsapp web is currenctly active" is the result of the connection itself and not a packet that is blockable. I'm not sure about it because it would take some time to catch it and investigate this.

**Comment by vittbol** [comment] 2018-03-16 12:46
It's okay, no need all this work. Thanks for your extension.

**Comment by vittbol** [comment] 2018-03-20 01:41
It just stopped working.
https://prnt.sc/itkick

**Comment by tomer8007** [comment] 2018-03-20 10:46
Will look at that as soon as I can.

**Comment by tomer8007** [comment] 2018-03-23 09:52
Okay, I just tested it and the extension is working fine for me.
What error are printed in the javascript console?

**Comment by tomer8007** [comment] 2018-05-02 17:55
##  **Update**

Google finally agreed to publish this extension as a new item live in the store, [right here, under the name WAIncognito](https://chrome.google.com/webstore/detail/waincognito/alhmbbnlcggfcjjfihglopfopcbigmil).

**Closed** 2018-05-26 19:48 UTC
Labels: help wanted
