### ISSUE TITLE
Error when sending messages

### ISSUE THREAD

**Issue by eduardokabello** [tomer8007/whatsapp-web-incognito#124] opened 2023-05-10 15:53 UTC
It's been a week since my whatsapp web started showing an error when sending a message.

When I open WhatsApp Web, it works normally for the first few messages (between 1 and 5 messages), after that it gives an error, as shown in the image.

![waincognito](https://github.com/tomer8007/whatsapp-web-incognito/assets/90769476/d1fdf07a-411b-4803-ba2e-64b7a450bfa4)

The message shown in the image is in Portuguese, and the translation is "An error has occurred. Click to learn more."

If I reload the page it works for the first few messages again, but the error returns again.

When I disable the plugin, WhatsApp Web works normally, without errors.

I installed the plugin on another computer, with a clean install of Chrome, without any other plugins, and the error also happens.

The version of WhatsApp Web I'm using is 2.2319.9

Has anyone had this error?

**Comment by tomer8007** [comment] 2023-05-11 06:05
Hi,
Thank you for opening an issue for this.

I would guess that this error could be related to the message interception functionality of the extension, but I'll need some red javascript errors to be sure.
Can you provide these?

**Comment by eduardokabello** [comment] 2023-05-11 13:23
![interception](https://github.com/tomer8007/whatsapp-web-incognito/assets/90769476/9af5ad67-07b3-468c-9f4a-775f322346e6)

![injected](https://github.com/tomer8007/whatsapp-web-incognito/assets/90769476/47557346-bc5d-45f0-8173-bc6bf88a6a4d)

**Comment by eduardokabello** [comment] 2023-05-11 13:44
![interception](https://github.com/tomer8007/whatsapp-web-incognito/assets/90769476/1c8891ee-7d9b-40bc-a04a-ad2d964ecf4e)

![injected](https://github.com/tomer8007/whatsapp-web-incognito/assets/90769476/ce597503-ee75-4117-b7ad-3318746f3d2b)

**Comment by tomer8007** [comment] 2023-05-11 19:07
Anything that appears before the `MD send failure`?

**Comment by tomer8007** [comment] 2023-05-15 17:46
@eduardokabello I don't see `MD send failure` in these logs. Are you sure these logs are written when you try to send a message without success?

**Comment by eduardokabello** [comment] 2023-05-15 21:36
@tomer8007 I certainly forgot to copy this part. I made the sequence again:

https://pastebin.com/xN8CACwF

**Comment by tomer8007** [comment] 2023-05-20 09:11
Hmm. According to the error
```
ui.js:603 Uncaught TypeError: Cannot read properties of null (reading 'split')
    at onNewMessageNodeAdded (ui.js:603:25)
    at MutationObserver.<anonymous> (ui.js:75:25)
```
It appears that the elements in your end do not have a `data-id` attribute.

And according to the error
```interception.js:677 [WhatsApp][3] -- sendMsgRecord: MD send failure```
It looks like something was messed up in the message interception flow.
Can you please
1. Tell me what version of WhatsApp Web are you using? I'm using 2.2321.6.
2. Try to type into the console 
```
WAPassthrough = true;
WAPassthroughWithDebug = true;
```
and look at the logs again?

**Comment by tomer8007** [comment] 2023-05-23 17:13
I don't see any indication to the message send failure  in your logs.
I need you to `WAdebugMode = true; WAPassthroughWithDebug = true;` and then trigger the error by trying to send a message without success. Also in debug mode I expect to see more messages.

**Comment by eduardokabello** [comment] 2023-05-23 19:37
Coincidence or not, after I enabled WAdebugMode = true; WAPassthroughWithDebug = true; before start send any message, I'm using WhatsApp at least for 1 hour without error.

**Comment by tomer8007** [comment] 2023-05-23 19:53
I think it's not a coincidence because `WAPassthroughWithDebug` disables some part of the interception. So if you could only `WAdebugMode = true` and restore the error, this would be good.

**Comment by eduardokabello** [comment] 2023-05-23 20:32
I started WhatsApp, put only WAdebugMode = true and the error come back

https://pastebin.com/crENP5KQ

**Comment by tomer8007** [comment] 2023-05-23 20:50
Uhh It's hard for me to debug it this way. I would expect more `[Out]` debug information before the `MD send failure` line. Perhaps there is something that you do that triggers this error that I don't. Can you describe exactly how to reproduce this or try it on another WhatsApp account?

**Comment by eduardokabello** [comment] 2023-05-24 23:52
Step by step action:

I installed a clean Edge browser and installed WAIncognito.

I opened a WhatsApp Web tab and I connected with a new WhatsApp account

I opened a console and put WAdebugMode = true;

I navigated in some messages and send some messages and leave browser opened and checking sometimes console messages.

In one moment, the looping error started without send any messages, and then, I tried to send a message and error happening again.

https://pastebin.com/05iq21c4

**Comment by tomer8007** [comment] 2023-05-29 18:43
Can you send at least one message successfully? I would expect to see something like `[Out] Sending binary with tag '' (152 bytes, decrypted): 
interception.js:534 <message id=​"3EB02714E3239A94137127" to=​"...@g.us" phash=​"2:​..." type=​"text">​…​</message>​` but I don't see it in your logs.

It appears that for some reason the sockets are getting closed in your end because something was screwed in the interception previously but at my end it looks fine.

**Comment by eduardokabello** [comment] 2023-05-30 06:36
Yes, I can send some messages successfully before error

Something like this?

interception.js:534 <message id=​"3EB081E09DEDA0F5CB7EC9" to=​"1321255888@c.us" type=​"text">​
<enc v="2" type="msg">
<unknown>[object ArrayBuffer]</unknown>
</enc>
​</message>​

See complete console capture: https://pastebin.com/W6kj8mDT

**Comment by eduardokabello** [comment] 2023-06-01 04:29
Chrome v114.0.5735.91
Edge v113.0.1774.57
WhatsApp Web v2.2322.15

**Comment by tomer8007** [comment] 2023-06-02 08:08
Now I'm using WhatsApp version 2.2323.4. But do you have the same problem in Chrome?

**Comment by eduardokabello** [comment] 2023-06-05 01:01
The same error in both browser, Chrome and Edge

**Comment by tomer8007** [comment] 2023-06-06 19:25
Still trying to reproduce this without success.

**Comment by eduardokabello** [comment] 2023-06-14 00:57
> Still trying to reproduce this without success. **EDIT**: Is there a chance this problem happens only for groups?

No, the problem happens with person to person messages

**Comment by ranggasan** [comment] 2023-07-03 02:07
Is there any solution about this issue?
Because I'm experiencing the same problem, unable to send messages after some times and need to reload the page to resend them

**Comment by tomer8007** [comment] 2023-07-03 05:31
I was able to reproduce this on my side only when sending messages to a group with a large number of participants. I suspect that this is caused by the same underlying reason as #127. Hopefully I could solve this one by solving #127 the next time I encounter it.

**Comment by ranggasan** [comment] 2023-07-03 06:54
> I was able to reproduce this on my side only when sending messages to a group with a large number of participants. I suspect that this is caused by the same underlying reason as #127. Hopefully I could solve this one by solving #127 the next time I encounter it.

For your additional information, it also happens in personal chat, like in the screenshot I attach above

**Comment by tomer8007** [comment] 2023-07-09 17:16
@ranggasan @eduardokabello Can you please tell me if version 2.0.6 seems to change anything?

**Comment by ranggasan** [comment] 2023-07-10 02:43
> @ranggasan @eduardokabello Can you please tell me if version 2.0.6 seems to change anything?

Unfortunately, the problem still persist

[![wa.jpg](https://i.postimg.cc/3R0Vf45K/wa.jpg)](https://postimg.cc/LYRxns87)

**Comment by ranggasan** [comment] 2023-07-11 03:18
I'm enabling wa web plus side by side with wa incognito, I think it's the cause of the issue. When I disable wa web plus, I found no issue.

I'm using wa web plus because I need its feature like blur messages and lock the screen. It would be nice if wa incognito has this features as well

**Comment by tomer8007** [comment] 2023-07-11 10:44
@ranggasan All I can see is that when I send messages to groups with a large number of participants, it initially shows the message as pending, and when I refresh the page, it shows the red warning sign like in your screenshot (even though the message was sent). So I suspect either this does not relate to WA Web Plus, or it is related and the problem I'm seeing is a different one.

Interesting finding though, I will test with WA Web Plus.

**Comment by eduardokabello** [comment] 2023-07-11 12:25
Unfortunately, the problem still persists here also.

Yes, I use WA Web Plus here too. I thought the issue was the WA Web Plus extension, but when I made a test with clean installation on Edge, the only extension installed was WAIncognito and the same error occurred.

**Comment by tomer8007** [comment] 2023-12-10 19:47
@eduardokabello @ranggasan Still happens in version 2.1.2?

**Comment by eduardokabello** [comment] 2023-12-12 16:20
> @eduardokabello @ranggasan Still happens in version 2.1.2?

Yes, still happens, but I found a way to partially work. Disabling “Don't send read confirmation” option. In this way, I don't get error anymore, but unfortunately I lose this function.

**Comment by ranggasan** [comment] 2023-12-13 02:41
> @eduardokabello @ranggasan Still happens in version 2.1.2?

Everything is working fine, I'm enabling all features in WA Web Incognito. And only enabling blur messages and lock screen in WA Web Plus

![wa](https://github.com/tomer8007/whatsapp-web-incognito/assets/28080386/1de82025-e6b0-489f-a867-ead4445a231c)

If I enable, **hide typing/hide recording/hide online/restore deleted messages**, it conflict with WA Web Incognito and problem persist

**Comment by tomer8007** [comment] 2024-01-21 20:22
@ranggasan @eduardokabello I did some refactoring to the message interception flow in version 2.1.3, changed the message restore feature, removed old code and added more sanity checks. Does this by chance fix the problem?

**Comment by eduardokabello** [comment] 2024-01-28 01:41
> @ranggasan @eduardokabello I did some refactoring to the message interception flow in version 2.1.3, changed the message restore feature, removed old code and added more sanity checks. Does this by chance fix the problem?

Unfortunately, the error still persists. To work, the option “Don't send read confirmation” needs to be disabled.

**Comment by ranggasan** [comment] 2024-01-29 09:38
> @ranggasan @eduardokabello I did some refactoring to the message interception flow in version 2.1.3, changed the message restore feature, removed old code and added more sanity checks. Does this by chance fix the problem?

Everything is working fine so far

**Comment by eduardokabello** [comment] 2024-01-29 12:24
> > @ranggasan @eduardokabello I did some refactoring to the message interception flow in version 2.1.3, changed the message restore feature, removed old code and added more sanity checks. Does this by chance fix the problem?
> 
> Everything is working fine so far

Even if you enable "hide typing/hide recording/hide online/restore deleted messages" options?

**Comment by ranggasan** [comment] 2024-01-31 02:30
> > > @ranggasan @eduardokabello I did some refactoring to the message interception flow in version 2.1.3, changed the message restore feature, removed old code and added more sanity checks. Does this by chance fix the problem?
> > 
> > 
> > Everything is working fine so far
> 
> Even if you enable "hide typing/hide recording/hide online/restore deleted messages" options?

I disabled those features because WA Web Incognito has them. I install WA Web Plus only to blur messages, lock screen and chat folder

**Comment by eduardokabello** [comment] 2024-03-21 12:47
> @eduardokabello @ranggasan I was able to reproduce the problem deterministically in cases where a message is sent together with a read receipt. I fixed the problem at least in these cases in [856da2f](https://github.com/tomer8007/whatsapp-web-incognito/commit/856da2f9dd97fac2dee3c91367dcf7bd0d8626d7). Please let me know if it fixes the problem for you.

Unfortunately, this error persists and about a week for now, another error started to happening (look at the image).

![wa error](https://github.com/tomer8007/whatsapp-web-incognito/assets/90769476/d35ebd64-7fd6-42ee-bfda-804c8b82e265)

I think there is a conflict about WA Web Plus (v4.8.9.2) and WAIncognito (v2.1.4 ) extensions, cause' when I disable WA Web Plus, the error from WAIncognito is gone.

**Comment by tomer8007** [comment] 2024-03-21 17:46
@eduardokabello This is another issue #159 .

**Comment by tomer8007** [comment] 2024-04-02 16:25
@eduardokabello @ranggasan What about the error when sending messages? still happening?

**Comment by tomer8007** [comment] 2024-04-03 20:04
@ranggasan OK, closing this issue.

But the warning shows up fine for me in version 2.3000, not sure why it doesn't for you. Maybe open a separate issue for this.

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/11458759/97fa3ff7-570e-479a-a015-c045bc10c4b9)

**Closed by tomer8007** 2024-04-03 20:04 UTC
Labels: bug, major
