### ISSUE TITLE
signalDecryptPrekeyWhisperMessage function is not working

### ISSUE THREAD

**Issue by wangsen2020** [tomer8007/whatsapp-web-incognito#94] opened 2022-06-17 11:43 UTC
`var messageKey = await MultiDevice.signalGetMessageKey(chainKeyData, message.counter, messageKeys);
    var keys = await libsignal.HKDF.deriveSecrets(messageKey, new ArrayBuffer(32), "WhisperMessageKeys");
    
    // here is  throw except
    var plaintext = await libsignal.crypto.decrypt(keys[0], toArrayBuffer(message.ciphertext), keys[2].slice(0, 16));
    // plaintext makes sense? good.
    return plaintext;`

I tried to fix it but it was too complicated.
 if you have  time, please check it, maybe it's a bug

**Comment by tomer8007** [comment] 2022-06-17 11:57
Do you have a javascript exception?

**Comment by wangsen2020** [comment] 2022-06-17 12:18
> Do you have a javascript exception to show? How to reproduce this?

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/38904770/174296576-d8a73f71-d075-4a74-8a76-b70765c27922.png">

**Comment by wangsen2020** [comment] 2022-06-17 12:44
I use the master branch, in core_injections.js inject this script
<img width="867" alt="image" src="https://user-images.githubusercontent.com/38904770/174300318-18aebdc9-16f7-4cce-afe8-8262c4bf5e95.png">
I mean when I receive a message，it break at 
`var plaintext = await libsignal.crypto.decrypt(keys[0], toArrayBuffer(message.ciphertext), keys[2].slice(0, 16));`
you can try it
I found the whatsapp js code and found it's right，I think the parameter is wrong

**Comment by tomer8007** [comment] 2022-06-17 12:53
Can you figure out why it's not injected in your case? Also how is the line `var plaintext = await libsignal.crypto.decrypt(keys[0], toArrayBuffer(message.ciphertext), keys[2].slice(0, 16));` relevant? I don't see it in the exception you sent.

**Comment by wangsen2020** [comment] 2022-06-17 13:04
it's injected my case，The problem with my feedback is that：
when I receive a message from others or from my whatsapp mobile, I can't get this message text.
so  I debug this source code and  found the code above throw a exception, this  exception was caught by interceptions.js.
so I screenshot a picture of console to you，The location where the exception is thrown is：
`var plaintext = await libsignal.crypto.decrypt(keys[0], toArrayBuffer(message.ciphertext), keys[2].slice(0, 16));`

**Comment by tomer8007** [comment] 2022-06-17 13:12
Do you have a screenshort of the exception with the `var plaintext = await libsignal.crypto.decrypt(keys[0], toArrayBuffer(message.ciphertext), keys[2].slice(0, 16));` line?

**Comment by wangsen2020** [comment] 2022-06-17 13:26
![Jun-17-2022 21-23-06](https://user-images.githubusercontent.com/38904770/174307269-19c291ba-ab48-40f1-9d33-3625f30c892c.gif)

**Comment by tomer8007** [comment] 2022-06-17 13:28
OK, but what is the exception message (`exception.message`)?

**Comment by wangsen2020** [comment] 2022-06-17 13:30
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/38904770/174308148-8f369918-2ed1-49e5-acaf-b62072711986.png">

**Comment by wangsen2020** [comment] 2022-06-17 14:53
It's work normally in waincognito， but when others send message to you  or you send message to others by your whatsapp mobile.
I want to get the message that others send to me, but  it's wrong when decrypt message, certainly you can ignore，because it don't affect waincognito functions

**Comment by wangsen2020** [comment] 2022-06-17 15:22
I would be grateful if you can decrypt the message, because I really need to listen to the returned event, of course, if it is difficult, just ignore it

**Comment by tomer8007** [comment] 2022-06-17 15:26
Does this happen only with voice message? How about groups? Anything that can help me understand the scenario is going to help.

**Comment by wangsen2020** [comment] 2022-06-19 06:22
I don't understand why you can't understand my feedback, maybe you've been silent on your wacognito product, what I'm feeding is not the read receipt, what I'm feeding back is that this code can't decrypt the returned information, I made it very clear , when someone sends you a message, you can't decrypt the content of the message, how can I describe this to you? You can found this problem as long as you debug it yourself

**Comment by wangsen2020** [comment] 2022-06-19 06:28
the code can‘t decrypt content of the message，if you can solve it，it's very wonderful，
If you don't know how to solve the decryption problem, just ignore it

**Comment by wangsen2020** [comment] 2022-06-19 06:46
> But I just tried to send a message and receive it and it works fine. Can you guess what are the special circumstances at which this happens

if you check your code，you will find when the code throw exception, you will return the original object  which  does not affect the parsing process of whatsapp，so you think it works fine.

As long as the message is decrypted, the error will be reported.  obviously

**Comment by tomer8007** [comment] 2022-06-19 17:14
My trouble is that, the decryption works for me:
![image](https://user-images.githubusercontent.com/11458759/174492686-d0d4e962-79d2-48d2-abae-0150d11388bd.png)

**Comment by wangsen2020** [comment] 2022-06-20 04:45
my whatsapp account 8618976917166，you send a message for me，I use common account not business account，whatsapp version 版本 2.2220.8

**Comment by wangsen2020** [comment] 2022-07-08 06:50
did you resolved this bug ？

**Comment by tomer8007** [comment] 2022-07-08 10:55
Sadly, no. It still works for me. 

It sounds like somehow there is a problem with the Signal database state. Does re-logging in change anything? Also did this bug start appearing for you right from the beginning?

**Comment by wangsen2020** [comment] 2022-07-18 09:22
> Sadly, no. It still works for me.
> 
> It sounds like somehow there is a problem with the Signal database state. Does re-logging in change anything? Also did this bug start appearing for you right from the beginning?

Is this source code give you some inspiration？
https://github.com/pedroslopez/whatsapp-web.js

**Comment by tomer8007** [comment] 2022-07-18 18:50
> `Is this source code give you some inspiration？`

No, it doesn't seem to do Signal message decryption. Have you tried the extension on other computers?

**Comment by tomer8007** [comment] 2023-03-16 20:04
Closing because I can't reproduce this.

**Closed by tomer8007** 2023-03-16 20:04 UTC
Labels: bug
