### ISSUE TITLE
Group Messages Crash Page with Minified React Error

### ISSUE THREAD

**Issue by BarAppTeam** [tomer8007/whatsapp-web-incognito#129] opened 2023-07-20 11:39 UTC
**Issue Title: Group Messages Crash Page with Minified React Error #130**

**Description:**
When clicking on a group to read the messages, the page crashes, and the console shows a Minified React error #130. The error message mentions that the full message can be found at [React Error Decoder](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=).

**Steps to Reproduce:**
1. Navigate to the chat list or any group.
2. Click on a group to open the conversation and read the messages.

**Expected Behavior:**
The group chat should open successfully, and the messages should be visible without any errors or crashes.

**Actual Behavior:**
Upon clicking on a group to read the messages, the page crashes, and the Minified React error #130 is thrown in the console.

**Additional Information:**
- This issue seems to be related to the rendering of the group chat component.
- It's possible that there's a bug in the React code or a misconfiguration causing this error.
- The error might be due to incorrect handling of undefined values in the React component.

**Environment:**
- Operating System: MacOS
- Browser: Chrome Version 115.0.5790.98 (Official Build) (x86_64)
- Application Version: 2.0.6

**Additional Information and Screenshots:**
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/77774766/027be5ee-d45f-4dd2-bde4-6c9ad743f67e)

**Comment by tomer8007** [comment] 2023-07-20 20:18
Yes, I also saw this happening sometimes, but unfortunately it's hard for me to reproduce this deterministically. I suspect that this is related to ba1d17fa943b04090ff0bc4ca0319c676d7083ae, so you could check if it's happening before this commit or not,

**Comment by tomer8007** [comment] 2023-07-20 20:29
BTW The `Caller at   Object.promise` error is raised from a function named `isLegitErrorStack` that's checking if the call stack is from a legit WhatsApp client or not.

**Comment by tomer8007** [comment] 2023-07-30 22:57
@BarAppTeam Thank you for the detailed report. I released version 1.0.7 and if you still have this error I will be glad to hear more on how to reproduce it.

**Comment by BarAppTeam** [comment] 2023-07-31 07:37
Hey @tomer8007 
Thank you for the help, but the problem still exists.
The error does not happen every time, but it is fixed after I refresh my page. Here are the steps to reproduce this error:

1. Open WhatsApp Web on my PC.
2. Click on a group to read the messages from them (it doesn't matter which type of chat it is).

Error:
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/77774766/e5cd6fef-cc6b-4c53-9499-f1f729c1f6fb)

**Comment by tomer8007** [comment] 2023-07-31 19:33
@BarAppTeam OK, I think I managed to change something in version 2.0.9. Please let me know

**Comment by tomer8007** [comment] 2023-08-11 12:21
@BarAppTeam Closing because of in-activity.

**Closed by tomer8007** 2023-08-11 12:21 UTC
Labels: bug
